# Generated by Django 5.2.15 on 2026-06-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
