# Generated by Django 5.2.15 on 2026-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverstatus',
            name='expected_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
