# Generated by Django 5.2.15 on 2026-06-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverstatus_expected_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverstatus',
            name='expected_return',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
